# Generated by Django 4.2.4 on 2023-08-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.TextField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.TextField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
